const API_BASE = 'https://api.twelvedata.com';
const WS_BASE = 'wss://ws.twelvedata.com/v1/quotes/price';

const SYMBOLS = { AUDCAD:'AUD/CAD', EURUSD:'EUR/USD', GBPUSD:'GBP/USD', USDJPY:'USD/JPY', XAUUSD:'XAU/USD', US30:'DJI' };
const INTERVALS = { S1:'1min', S5:'1min', S15:'1min', S30:'1min', M1:'1min', M5:'5min', M15:'15min', H1:'1h', H4:'4h', D1:'1day' };
const INTERVAL_SECONDS = { S1:1, S5:5, S15:15, S30:30, M1:60, M5:300, M15:900, H1:3600, H4:14400, D1:86400 };
const CACHE_TTL=5*60*1000, SOCKET_IDLE_GRACE=1500, MAX_WS_SYMBOLS=8;
const candleCache=new Map();

export const toTwelveSymbol=symbol=>SYMBOLS[symbol]??symbol;
export const toTwelveInterval=timeframe=>INTERVALS[timeframe]??'1min';
export const timeframeSeconds=timeframe=>INTERVAL_SECONDS[timeframe]??60;
function apiKey(){const key=import.meta.env.VITE_TWELVE_DATA_API_KEY;if(!key)throw new Error('Missing VITE_TWELVE_DATA_API_KEY');return key;}
function parseUtcDatetime(value){if(!value)return null;const iso=value.includes('T')?value:value.replace(' ','T');const ms=Date.parse(`${iso}Z`);return Number.isFinite(ms)?Math.floor(ms/1000):null;}
function cacheKey(symbol,timeframe,outputsize){return `${symbol}:${timeframe}:${outputsize}`;}

export async function fetchCandles(symbol,timeframe,outputsize=500,signal){const key=cacheKey(symbol,timeframe,outputsize),cached=candleCache.get(key);if(cached&&Date.now()-cached.savedAt<CACHE_TTL)return cached.bars.map(bar=>({...bar}));const params=new URLSearchParams({symbol:toTwelveSymbol(symbol),interval:toTwelveInterval(timeframe),outputsize:String(outputsize),timezone:'UTC',order:'asc',apikey:apiKey()});const response=await fetch(`${API_BASE}/time_series?${params}`,{signal}),body=await response.json();if(!response.ok||body?.status==='error')throw new Error(body?.message||`Twelve Data request failed (${response.status})`);const bars=(body?.values||[]).map(item=>({time:parseUtcDatetime(item.datetime),open:Number(item.open),high:Number(item.high),low:Number(item.low),close:Number(item.close),volume:Number.isFinite(Number(item.volume))?Number(item.volume):null})).filter(bar=>bar.time&&[bar.open,bar.high,bar.low,bar.close].every(Number.isFinite));candleCache.set(key,{savedAt:Date.now(),bars});return bars.map(bar=>({...bar}));}
export function mergeLiveBarIntoCache(symbol,timeframe,bar,outputsize=500){const key=cacheKey(symbol,timeframe,outputsize),cached=candleCache.get(key);if(!cached)return;const bars=cached.bars.slice(),last=bars[bars.length-1];if(last?.time===bar.time)bars[bars.length-1]={...bar};else if(!last||bar.time>last.time)bars.push({...bar});while(bars.length>outputsize)bars.shift();candleCache.set(key,{savedAt:Date.now(),bars});}

class TwelveDataSocketManager{
 constructor(){this.socket=null;this.listeners=new Map();this.subscribedSymbols=new Set();this.pendingSymbols=new Set();this.symbolOrder=[];this.reconnectTimer=null;this.idleTimer=null;this.heartbeat=null;this.retry=0;this.intentionalClose=false;}
 subscribe(symbol,onTick,onError,onStatus){const tdSymbol=toTwelveSymbol(symbol);this.cancelIdleClose();let set=this.listeners.get(tdSymbol);const firstForSymbol=!set;if(!set){set=new Set();this.listeners.set(tdSymbol,set);this.touch(tdSymbol);}const listener={onTick,onError,onStatus};set.add(listener);this.ensureConnected();if(firstForSymbol&&this.socket?.readyState===WebSocket.OPEN)this.requestSubscribe(tdSymbol);return()=>{const current=this.listeners.get(tdSymbol);if(!current)return;current.delete(listener);if(!current.size){this.listeners.delete(tdSymbol);this.symbolOrder=this.symbolOrder.filter(x=>x!==tdSymbol);if(this.socket?.readyState===WebSocket.OPEN&&(this.subscribedSymbols.has(tdSymbol)||this.pendingSymbols.has(tdSymbol)))this.sendSubscription('unsubscribe',tdSymbol);this.subscribedSymbols.delete(tdSymbol);this.pendingSymbols.delete(tdSymbol);}if(!this.listeners.size)this.scheduleIdleClose();};}
 touch(symbol){this.symbolOrder=this.symbolOrder.filter(x=>x!==symbol);this.symbolOrder.push(symbol);}
 ensureConnected(){if(!this.listeners.size||this.socket?.readyState===WebSocket.OPEN||this.socket?.readyState===WebSocket.CONNECTING)return;this.intentionalClose=false;this.socket=new WebSocket(`${WS_BASE}?apikey=${encodeURIComponent(apiKey())}`);this.socket.addEventListener('open',()=>{this.retry=0;this.subscribedSymbols.clear();this.pendingSymbols.clear();for(const symbol of this.listeners.keys())this.requestSubscribe(symbol);this.startHeartbeat();});this.socket.addEventListener('message',event=>{try{const data=JSON.parse(event.data);if(data?.event==='price'){this.handlePrice(data);return;}if(data?.event==='subscribe-status'||data?.event==='unsubscribe-status'){this.handleStatus(data);return;}}catch(error){this.emitError(error);}});this.socket.addEventListener('error',()=>this.emitError(new Error('Twelve Data WebSocket unavailable')));this.socket.addEventListener('close',()=>{this.stopHeartbeat();this.socket=null;this.subscribedSymbols.clear();this.pendingSymbols.clear();if(!this.intentionalClose&&this.listeners.size)this.scheduleReconnect();});}
 requestSubscribe(symbol){if(this.subscribedSymbols.has(symbol)||this.pendingSymbols.has(symbol))return;while(this.subscribedSymbols.size+this.pendingSymbols.size>=MAX_WS_SYMBOLS){const victim=this.symbolOrder.find(s=>s!==symbol&&!this.listeners.has(s));if(!victim){this.emitSymbolError(symbol,new Error(`Twelve Data Basic WebSocket limit reached (${MAX_WS_SYMBOLS} symbols)`));return;}this.sendSubscription('unsubscribe',victim);this.subscribedSymbols.delete(victim);this.pendingSymbols.delete(victim);this.symbolOrder=this.symbolOrder.filter(s=>s!==victim);}this.pendingSymbols.add(symbol);this.sendSubscription('subscribe',symbol);}
 handleStatus(data){const successes=Array.isArray(data.success)?data.success:[],fails=Array.isArray(data.fails)?data.fails:[];for(const item of successes){const symbol=item.symbol;if(!symbol)continue;if(data.event==='subscribe-status'){this.pendingSymbols.delete(symbol);this.subscribedSymbols.add(symbol);this.touch(symbol);}else{this.pendingSymbols.delete(symbol);this.subscribedSymbols.delete(symbol);}this.emitStatus(symbol,{event:data.event,status:'ok',details:item});}for(const item of fails){const symbol=item.symbol||item?.meta?.symbol;if(symbol){this.pendingSymbols.delete(symbol);if(data.event==='subscribe-status')this.subscribedSymbols.delete(symbol);this.emitStatus(symbol,{event:data.event,status:'error',details:item});this.emitSymbolError(symbol,new Error(item.message||`Twelve Data ${data.event} failed for ${symbol}`));}}if(data.status==='error'&&!fails.length)this.emitError(new Error(data.message||`Twelve Data ${data.event} failed`));}
 handlePrice(data){const price=Number(data.price),time=Number(data.timestamp);if(!Number.isFinite(price)||!Number.isFinite(time))return;const bid=data.bid==null?null:Number(data.bid),ask=data.ask==null?null:Number(data.ask),targets=this.listeners.get(data.symbol);if(!targets)return;const tick={price,bid:Number.isFinite(bid)?bid:null,ask:Number.isFinite(ask)?ask:null,time:Math.floor(time),timestamp:Math.floor(time),symbol:data.symbol,dayVolume:data.day_volume==null?null:Number(data.day_volume)};for(const listener of targets)listener.onTick(tick);}
 sendSubscription(action,symbol){if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({action,params:{symbols:symbol}}));}
 startHeartbeat(){this.stopHeartbeat();this.heartbeat=window.setInterval(()=>{if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({action:'heartbeat'}));},10000);}
 stopHeartbeat(){if(this.heartbeat){window.clearInterval(this.heartbeat);this.heartbeat=null;}}
 scheduleReconnect(){if(this.reconnectTimer)return;const delay=Math.min(1000*2**this.retry,30000);this.retry+=1;this.reconnectTimer=window.setTimeout(()=>{this.reconnectTimer=null;this.ensureConnected();},delay);}
 scheduleIdleClose(){this.cancelIdleClose();this.idleTimer=window.setTimeout(()=>{this.idleTimer=null;if(!this.listeners.size)this.disconnect();},SOCKET_IDLE_GRACE);}
 cancelIdleClose(){if(this.idleTimer){window.clearTimeout(this.idleTimer);this.idleTimer=null;}}
 emitStatus(symbol,status){for(const listener of this.listeners.get(symbol)||[])listener.onStatus?.(status);}
 emitSymbolError(symbol,error){for(const listener of this.listeners.get(symbol)||[])listener.onError?.(error);}
 emitError(error){for(const set of this.listeners.values())for(const listener of set)listener.onError?.(error);}
 disconnect(){this.intentionalClose=true;this.cancelIdleClose();if(this.reconnectTimer){window.clearTimeout(this.reconnectTimer);this.reconnectTimer=null;}this.stopHeartbeat();this.subscribedSymbols.clear();this.pendingSymbols.clear();const socket=this.socket;this.socket=null;if(socket&&socket.readyState<2)socket.close();}
}

const socketManager=new TwelveDataSocketManager();
export function subscribePrice(symbol,onTick,onError,onStatus){return socketManager.subscribe(symbol,onTick,onError,onStatus);}
