import { createRequire } from 'node:module';
import process from 'node:process';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
let browser;
(async () => {
  const output = process.env.CHART_QA_OUTPUT || 'tests/ui/artifacts';
  fs.mkdirSync(output, { recursive: true });
  browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined, headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.CHART_QA_URL || 'http://127.0.0.1:5173/tests/fixtures/chart-tools.html');
  await page.getByRole('button', { name: 'Add Exponential Moving Average', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelectorAll('canvas').length > 0);
  await page.screenshot({ path: path.resolve(output, 'acg-indicators-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'On chart', exact: true }).click();
  await page.getByRole('button', { name: 'Edit EMA', exact: true }).click();
  await page.getByLabel('Length', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  assert.match(await page.getByRole('alert').innerText(), /whole number/);
  assert.equal(await page.evaluate(() => window.chartToolsQA.indicators[0].settings.period), 20);
  await page.getByLabel('Length', { exact: true }).fill('55');
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  assert.equal(await page.evaluate(() => window.chartToolsQA.indicators[0].settings.period), 55);
  await page.getByRole('button', { name: 'Edit EMA', exact: true }).click();
  await page.getByLabel('Length', { exact: true }).fill('100');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.chartToolsQA.indicators[0].settings.period), 55);
  await page.getByRole('button', { name: 'Edit EMA', exact: true }).click();
  await page.getByRole('button', { name: 'Style', exact: true }).click();
  await page.screenshot({ path: path.resolve(output, 'acg-indicator-settings.png'), fullPage: true });
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByLabel('Search indicators', { exact: true }).fill('relative strength');
  await page.getByRole('button', { name: 'Add Relative Strength Index', exact: true }).click();
  assert.equal(await page.evaluate(() => window.chartToolsQA.indicators.filter(item => item.id === 'rsi').length), 2);
  await page.getByRole('button', { name: 'Clear search', exact: true }).click();
  await page.getByTitle('Trend line', { exact: true }).click();
  const svg = page.locator('.fixture-chart svg.touch-none');
  const box = await svg.boundingBox();
  await page.mouse.move(box.x + 170, box.y + 200);
  await page.mouse.down();
  await page.mouse.move(box.x + 430, box.y + 280, { steps: 14 });
  await page.mouse.up();
  await page.waitForFunction(() => window.chartToolsQA.drawings().length === 1);
  const before = await page.evaluate(() => window.chartToolsQA.drawings());
  await page.getByTitle('Drawing properties', { exact: true }).click();
  await page.getByRole('button', { name: 'Appearance color #f0c35c', exact: true }).click();
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  assert.equal(await page.evaluate(() => window.chartToolsQA.drawings()[0].style.color), '#f0c35c');
  await page.getByTitle('Drawing properties', { exact: true }).click();
  await page.screenshot({ path: path.resolve(output, 'acg-drawing-properties.png'), fullPage: true });
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByTitle('Deselect', { exact: true }).click();
  await page.mouse.move(box.x + 300, box.y + 240);
  await page.mouse.down();
  await page.mouse.move(box.x + 330, box.y + 300, { steps: 8 });
  await page.waitForFunction(original => JSON.stringify(window.chartToolsQA.drawings()[0].a) !== JSON.stringify(original), before[0].a);
  await page.keyboard.press('Escape');
  await page.mouse.up();
  assert.deepEqual((await page.evaluate(() => window.chartToolsQA.drawings()))[0].a, before[0].a, 'Escape restores anchor');
  // Drawing state must remain unchanged while the chart rescales.
  const anchorBeforeZoom = await svg.locator('line').last().getAttribute('x1');
  await page.mouse.move(box.x + 300, box.y + 180);
  await page.mouse.wheel(0, -300);
  await page.waitForFunction(oldX => document.querySelector('.fixture-chart svg.touch-none line:last-of-type')?.getAttribute('x1') !== oldX, anchorBeforeZoom);
  assert.deepEqual((await page.evaluate(() => window.chartToolsQA.drawings()))[0].a, before[0].a);
  assert.ok((await svg.boundingBox()).height < (await page.locator('.fixture-chart').boundingBox()).height - 100, 'Drawings stay in the price pane');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Search indicators', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.resolve(output, 'acg-indicators-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No page overflow at 390px');
  await page.setViewportSize({ width: 320, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No page overflow at 320px');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(process.env.CHART_QA_URL || 'http://127.0.0.1:5173/tests/fixtures/chart-tools.html');
  await mobile.getByRole('button', { name: 'On chart', exact: true }).tap();
  await mobile.getByRole('button', { name: 'Edit EMA', exact: true }).tap();
  await mobile.getByRole('button', { name: 'Visibility', exact: true }).tap();
  await mobile.getByRole('button', { name: '5m', exact: true }).tap();
  await mobile.getByRole('button', { name: '1h', exact: true }).tap();
  await mobile.getByRole('button', { name: 'Apply', exact: true }).tap();
  assert.deepEqual(await mobile.evaluate(() => window.chartToolsQA.indicators[0].settings.timeframeVisibility), ['M5', 'H1']);
  await mobile.getByTitle('Trend line', { exact: true }).tap();
  const touchBox = await mobile.locator('.fixture-chart svg.touch-none').boundingBox();
  await mobile.touchscreen.tap(touchBox.x + 45, touchBox.y + 150);
  await mobile.touchscreen.tap(touchBox.x + 155, touchBox.y + 200);
  await mobile.waitForFunction(() => window.chartToolsQA.drawings().length === 1);
  await mobile.getByTitle('Drawing properties', { exact: true }).tap();
  await mobile.getByRole('button', { name: 'Visibility', exact: true }).tap();
  await mobile.getByRole('button', { name: '1m', exact: true }).tap();
  await mobile.getByRole('button', { name: 'Apply', exact: true }).tap();
  assert.deepEqual(await mobile.evaluate(() => window.chartToolsQA.drawings()[0].timeframeVisibility), ['M1']);
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.resolve(output, 'results.json'), JSON.stringify({ passed: true, checks: ['search by full name', 'add instance', 'input validation', 'apply', 'cancel', 'line creation', 'drawing style', 'Escape drag rollback', '390px and 320px overflow', 'zoom preserves anchors', 'price-pane drawing bounds', 'touch drawing creation', 'touch settings and multi-timeframe visibility', 'no browser errors'] }, null, 2));
  await browser.close();
  console.log('Chart UI checks passed.');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
