import React, { useMemo, useState } from 'react';
import { BarChart3, CandlestickChart, ChartNoAxesCombined, ChevronDown, Clock3, Crosshair, History, List, MoreHorizontal, MousePointer2, Search, Settings, SlidersHorizontal, Target, TrendingUp } from 'lucide-react';
import TradingChart from './components/TradingChart.jsx';
import { useMarketData } from './hooks/useMarketData.js';
import './App.css';

const seedMarkets = [
  { symbol:'AUDCAD', bid:'0.99368', ask:'0.99373', change:'-0.11%' },
  { symbol:'EURUSD', bid:'1.08421', ask:'1.08424', change:'+0.06%' },
  { symbol:'GBPUSD', bid:'1.26903', ask:'1.26907', change:'-0.12%' },
  { symbol:'USDJPY', bid:'156.284', ask:'156.291', change:'+0.21%' },
  { symbol:'XAUUSD', bid:'2648.30', ask:'2648.60', change:'+0.34%' },
  { symbol:'US30', bid:'42,910', ask:'42,915', change:'+0.08%' },
];
const positions = [
  { ticket:'1048101', symbol:'AUDCAD', type:'Buy', volume:'0.01', open:'0.99342', sl:'–', tp:'–', swap:'-0.06', profit:'+0.18' },
  { ticket:'1048092', symbol:'EURUSD', type:'Sell', volume:'0.02', open:'1.08460', sl:'1.08600', tp:'–', swap:'-0.02', profit:'+0.78' },
];
const timeframes=['M1','M5','M15','H1','H4','D1'];

function ExecutionBar({ market }){ const [volume,setVolume]=useState(0.10); return <div className="execution"><button className="quote sell"><small>SELL · DEMO</small><strong>{market.bid}</strong></button><div className="volume"><span>Volume</span><div><button onClick={()=>setVolume(v=>Math.max(.01, +(v-.01).toFixed(2)))}>−</button><b>{volume.toFixed(2)}</b><button onClick={()=>setVolume(v=>+(v+.01).toFixed(2))}>+</button></div></div><button className="quote buy"><small>BUY · DEMO</small><strong>{market.ask}</strong></button></div> }
function PositionRows({mobile=false}){ return <>{positions.map(p=> mobile ? <div className="mobile-position" key={p.ticket}><div><b>{p.symbol}</b><small>{p.type} {p.volume} · {p.open}</small></div><strong>+${p.profit.replace('+','')}</strong></div> : <div className="position-row" key={p.ticket}><b>{p.ticket}</b><b>{p.symbol}</b><span className={p.type==='Buy'?'positive':'negative'}>{p.type}</span><span>{p.volume}</span><b>{p.open}</b><span>{p.sl}</span><span>{p.tp}</span><span>{p.swap}</span><b className="positive">{p.profit}</b></div>)}</> }
function Tabs(){return <div className="tabs"><b>Positions (2)</b><span>Orders (0)</span><span>History</span></div>}
function Mobile({ market }){const [tf,setTf]=useState('M1');return <main className="mobile-terminal"><header className="mobile-head"><div><b>ACG Trader</b><i></i></div><div className="symbol-line"><div><h1>{market.symbol} <ChevronDown size={16}/></h1><p>GoCharting chart data · attributed</p></div><div className="price"><strong>{market.bid}</strong><small>demo shell quote</small></div></div></header><div className="mobile-timeframes">{['M1','M5','M15','H1','H4'].map(x=><button className={tf===x?'active':''} onClick={()=>setTf(x)} key={x}>{x==='M1'?'1m':x.toLowerCase()}</button>)}</div><section className="mobile-chart"><TradingChart compact symbol={market.symbol} timeframe={tf}/></section><div className="mobile-tools"><Crosshair/><span>ƒx</span><TrendingUp/><ChartNoAxesCombined/><span>T</span><Target/></div><ExecutionBar market={market}/><section className="mobile-positions"><Tabs/><PositionRows mobile/></section><nav className="bottom-nav"><button><List/><small>Quotes</small></button><button className="active"><CandlestickChart/><small>Chart</small></button><button><SlidersHorizontal/><small>Trade</small></button><button><Clock3/><small>History</small></button><button><MoreHorizontal/><small>More</small></button></nav></main>}
function Desktop({ markets, activeSymbol, setActiveSymbol }){const [tf,setTf]=useState('M1'); const market=useMemo(()=>markets.find(m=>m.symbol===activeSymbol)||markets[0],[markets,activeSymbol]);return <main className="desktop-terminal"><div className="ticker">{markets.map(m=><button className="ticker-item" onClick={()=>setActiveSymbol(m.symbol)} key={m.symbol}><b>{m.symbol} <em>{m.bid}</em></b><span className={m.change.startsWith('+')?'positive':'negative'}>{m.change}</span></button>)}</div><div className="accountbar"><div className="brand"><span>ACG</span><b>TRADER</b></div>{[['1048217','Demo'],['Balance','100,000.00'],['Equity','100,128.40'],['Margin','312.00'],['Free Margin','99,816.40'],['Margin Level','32,092%'],['P/L','+128.40']].map(([a,b])=><div className="metric" key={a}><span>{a}</span><b className={a==='Margin Level'||a==='P/L'?'positive':''}>{b}</b></div>)}<div className="live">CHART<br/><b>GC</b></div><Settings/></div><div className="workspace"><aside className="sidebar">{[[MousePointer2,'Trade'],[Search,'Watchlist'],[BarChart3,'Positions'],[Target,'Orders'],[History,'History'],[Settings,'Settings']].map(([Icon,label],i)=><button className={i===0?'active':''} key={label}><Icon/><span>{label}</span></button>)}</aside><section className="center"><div className="chart-head"><b>{market.symbol}</b><span className="live-pill">GOCHARTING</span>{timeframes.map(x=><button className={tf===x?'active':''} onClick={()=>setTf(x)} key={x}>{x}</button>)}<div className="head-tools"><CandlestickChart/><ChartNoAxesCombined/><SlidersHorizontal/></div></div><div className="chart-area"><div className="draw-tools"><MousePointer2/><Crosshair/><TrendingUp/><Target/><span>T</span></div><TradingChart symbol={market.symbol} timeframe={tf}/></div><ExecutionBar market={market}/><div className="desktop-positions"><Tabs/><div className="position-head"><span>Ticket</span><span>Symbol</span><span>Type</span><span>Volume</span><span>Open</span><span>S/L</span><span>T/P</span><span>Swap</span><span>Profit</span></div><PositionRows/></div></section><aside className="watch"><div className="watch-title"><b>MARKET WATCH · DEMO</b><div><Search size={16}/><MoreHorizontal size={16}/></div></div><div className="watch-head"><span>Symbol</span><span>Bid</span><span>Ask</span><span>Chg%</span></div>{markets.map(m=><button className={`watch-row ${m.symbol===activeSymbol?'selected':''}`} onClick={()=>setActiveSymbol(m.symbol)} key={m.symbol}><b>{m.symbol}</b><b className={m.change.startsWith('+')?'positive':'negative'}>{m.bid}</b><span>{m.ask}</span><b className={m.change.startsWith('+')?'positive':'negative'}>{m.change}</b></button>)}</aside></div></main>}
export default function App(){const { markets }=useMarketData(seedMarkets); const [activeSymbol,setActiveSymbol]=useState('AUDCAD'); const active=useMemo(()=>markets.find(m=>m.symbol===activeSymbol)||markets[0],[markets,activeSymbol]);return <><div className="mobile-only"><Mobile market={active}/></div><div className="desktop-only"><Desktop markets={markets} activeSymbol={activeSymbol} setActiveSymbol={setActiveSymbol}/></div></>}
