import React, { useState } from 'react';
import { BarChart3, CandlestickChart, ChartNoAxesCombined, ChevronDown, Clock3, Crosshair, History, List, MoreHorizontal, MousePointer2, Search, Settings, SlidersHorizontal, Target, TrendingUp } from 'lucide-react';
import TradingChart from './components/TradingChart.jsx';
import useMarketData from './hooks/useMarketData.js';
import { SYMBOLS } from './services/marketData.js';
import './App.css';

const positions=[{ticket:'1048101',symbol:'AUDCAD',type:'Buy',volume:'0.01',open:'0.99342',sl:'–',tp:'–',swap:'-0.06',profit:'+0.18'},{ticket:'1048092',symbol:'EURUSD',type:'Sell',volume:'0.02',open:'1.08460',sl:'1.08600',tp:'–',swap:'-0.02',profit:'+0.78'}];
const timeframes=['M1','M5','M15','H1','H4','D1'];
const fmt=(value,symbol)=>value==null?'—':Number(value).toFixed(symbol==='USDJPY'?3:symbol==='XAUUSD'?2:5);

function ExecutionBar({quote,symbol}){const [volume,setVolume]=useState(.10);return <div className="execution"><button className="quote sell"><small>SELL</small><strong>{fmt(quote?.bid,symbol)}</strong></button><div className="volume"><span>Volume</span><div><button onClick={()=>setVolume(v=>Math.max(.01,+(v-.01).toFixed(2)))}>−</button><b>{volume.toFixed(2)}</b><button onClick={()=>setVolume(v=>+(v+.01).toFixed(2))}>+</button></div></div><button className="quote buy"><small>BUY</small><strong>{fmt(quote?.ask,symbol)}</strong></button></div>}
function PositionRows({mobile=false}){return <>{positions.map(p=>mobile?<div className="mobile-position" key={p.ticket}><div><b>{p.symbol}</b><small>{p.type} {p.volume} · {p.open}</small></div><strong>+${p.profit.replace('+','')}</strong></div>:<div className="position-row" key={p.ticket}><b>{p.ticket}</b><b>{p.symbol}</b><span className={p.type==='Buy'?'positive':'negative'}>{p.type}</span><span>{p.volume}</span><b>{p.open}</b><span>{p.sl}</span><span>{p.tp}</span><span>{p.swap}</span><b className="positive">{p.profit}</b></div>)}</>}
function Tabs(){return <div className="tabs"><b>Positions (2)</b><span>Orders (0)</span><span>History</span></div>}

function Mobile(){const [tf,setTf]=useState('M1');const [symbol,setSymbol]=useState('AUDCAD');const {quote,status}=useMarketData(symbol);const meta=SYMBOLS.find(x=>x.symbol===symbol);return <main className="mobile-terminal"><header className="mobile-head"><div><b>ACG Trader</b><i className={status==='live'?'online':''}></i></div><div className="symbol-line"><div><h1>{symbol.slice(0,3)}/{symbol.slice(3)} <ChevronDown size={16}/></h1><p>{meta?.description}</p></div><div className="price"><strong>{fmt(quote?.bid,symbol)}</strong><small>{quote?.change??status}</small></div></div></header><div className="mobile-timeframes">{['M1','M5','M15','H1','H4'].map(x=><button className={tf===x?'active':''} onClick={()=>setTf(x)} key={x}>{x==='M1'?'1m':x.toLowerCase()}</button>)}</div><section className="mobile-chart"><TradingChart compact symbol={symbol} timeframe={tf}/></section><div className="mobile-tools"><Crosshair/><span>ƒx</span><TrendingUp/><ChartNoAxesCombined/><span>T</span><Target/></div><ExecutionBar quote={quote} symbol={symbol}/><section className="mobile-positions"><Tabs/><PositionRows mobile/></section><nav className="bottom-nav"><button><List/><small>Quotes</small></button><button className="active"><CandlestickChart/><small>Chart</small></button><button><SlidersHorizontal/><small>Trade</small></button><button><Clock3/><small>History</small></button><button><MoreHorizontal/><small>More</small></button></nav></main>}

function Desktop(){const [tf,setTf]=useState('M1');const [symbol,setSymbol]=useState('AUDCAD');const {quotes,quote,status}=useMarketData(symbol);return <main className="desktop-terminal"><div className="ticker">{SYMBOLS.map(m=>{const q=quotes[m.symbol];return <div key={m.symbol} onClick={()=>setSymbol(m.symbol)}><b>{m.symbol} <em>{fmt(q?.bid,m.symbol)}</em></b><span className={String(q?.change).startsWith('+')?'positive':'negative'}>{q?.change??'—'}</span></div>})}</div><div className="accountbar"><div className="brand"><span>ACG</span><b>TRADER</b></div>{[['1048217','Demo'],['Balance','100,000.00'],['Equity','100,128.40'],['Margin','312.00'],['Free Margin','99,816.40'],['Margin Level','32,092%'],['P/L','+128.40']].map(([a,b])=><div className="metric" key={a}><span>{a}</span><b className={a==='Margin Level'||a==='P/L'?'positive':''}>{b}</b></div>)}<div className="live">{status}<br/><b>market</b></div><Settings/></div><div className="workspace"><aside className="sidebar">{[[MousePointer2,'Trade'],[Search,'Watchlist'],[BarChart3,'Positions'],[Target,'Orders'],[History,'History'],[Settings,'Settings']].map(([Icon,label],i)=><button className={i===0?'active':''} key={label}><Icon/><span>{label}</span></button>)}</aside><section className="center"><div className="chart-head"><b>{symbol}</b><span className="live-pill">{status.toUpperCase()}</span>{timeframes.map(x=><button className={tf===x?'active':''} onClick={()=>setTf(x)} key={x}>{x}</button>)}<div className="head-tools"><CandlestickChart/><ChartNoAxesCombined/><SlidersHorizontal/></div></div><div className="chart-area"><div className="draw-tools"><MousePointer2/><Crosshair/><TrendingUp/><Target/><span>T</span></div><TradingChart symbol={symbol} timeframe={tf}/></div><ExecutionBar quote={quote} symbol={symbol}/><div className="desktop-positions"><Tabs/><div className="position-head"><span>Ticket</span><span>Symbol</span><span>Type</span><span>Volume</span><span>Open</span><span>S/L</span><span>T/P</span><span>Swap</span><span>Profit</span></div><PositionRows/></div></section><aside className="watch"><div className="watch-title"><b>MARKET WATCH</b><div><Search size={16}/><MoreHorizontal size={16}/></div></div><div className="watch-head"><span>Symbol</span><span>Bid</span><span>Ask</span><span>Chg%</span></div>{SYMBOLS.map(m=>{const q=quotes[m.symbol];return <div className="watch-row" key={m.symbol} onClick={()=>setSymbol(m.symbol)}><b>{m.symbol}</b><b>{fmt(q?.bid,m.symbol)}</b><span>{fmt(q?.ask,m.symbol)}</span><b className={String(q?.change).startsWith('+')?'positive':'negative'}>{q?.change??'—'}</b></div>})}<div className="instrument"><div><b>{symbol}</b></div><small>{SYMBOLS.find(x=>x.symbol===symbol)?.description}</small><strong>{fmt(quote?.bid,symbol)} <em>{quote?.change??'—'}</em></strong></div></aside></div></main>}
export default function App(){return <><div className="mobile-only"><Mobile/></div><div className="desktop-only"><Desktop/></div></>}
